libbpm: Error/warning messages
Error/warning messages
Detailed Description
Files
file bpm_error.c
file bpm_messages.h
libbpm error/warning messages
file bpm_warning.c
Functions
EXTERN void bpm_error (char *msg, char *f, int l)
EXTERN void bpm_warning (char *msg, char *f, int l)
Function Documentation
EXTERN void bpm_error (char * msg, char * f, int l)
Prints an error message in a standard format
Parameters:
msg the error messages, without end of line character
f the file position (__FILE__)
l the line in the file (__LINE__)
Returns:
void
Definition at line 9 of file bpm_error.c.
References libbpm_evtnum.
Referenced by _expand_complex_polynomial(), add_mode_response(), ana_set_cutfn(), apply_filter(), calibrate(), check_saturation(), complexfft(), complexwf(), complexwf_add(), complexwf_add_ampnoise(), complexwf_add_cwtone(), complexwf_add_dcywave(), complexwf_add_noise(), complexwf_add_phasenoise(), complexwf_bias(), complexwf_compat(), complexwf_copy(), complexwf_copy_new(), complexwf_divide(), complexwf_getamp(), complexwf_getamp_new(), complexwf_getimag(), complexwf_getimag_new(), complexwf_getphase(), complexwf_getphase_new(), complexwf_getreal(), complexwf_getreal_new(), complexwf_multiply(), complexwf_print(), complexwf_reset(), complexwf_scale(), complexwf_setfunction(), complexwf_setimag(), complexwf_setreal(), complexwf_setvalues(), complexwf_subset(), complexwf_subtract(), correct_gain(), create_filter(), create_resonator_representation(), create_splane_representation(), ddc_initialise(), ddc_sample_waveform(), ddc_waveform(), digitise(), doublewf(), doublewf_add(), doublewf_add_ampnoise(), doublewf_add_cwtone(), doublewf_add_dcywave(), doublewf_basic_stats(), doublewf_bias(), doublewf_cast(), doublewf_cast_new(), doublewf_compat(), doublewf_copy(), doublewf_copy_new(), doublewf_derive(), doublewf_divide(), doublewf_getvalue(), doublewf_integrate(), doublewf_multiply(), doublewf_print(), doublewf_resample(), doublewf_reset(), doublewf_scale(), doublewf_setvalues(), doublewf_subset(), doublewf_subtract(), downmix_waveform(), fft_gen_tables(), fft_initialise(), fft_waveform(), filter_impulse_response(), filter_step_response(), fit_fft(), fit_fft_prepare(), fit_waveform(), gaussian_filter_coeffs(), generate_bpmsignal(), generate_diodesignal(), get_bpmhit(), get_bpmhits(), get_IQ(), get_mode_response(), get_pedestal(), get_pos(), get_slope(), get_t0(), gsl_block_alloc(), gsl_matrix_column(), gsl_matrix_submatrix(), gsl_matrix_swap_columns(), gsl_vector_subvector(), intwf(), intwf_add(), intwf_add_ampnoise(), intwf_add_cwtone(), intwf_add_dcywave(), intwf_basic_stats(), intwf_bias(), intwf_cast(), intwf_cast_new(), intwf_compat(), intwf_copy(), intwf_copy_new(), intwf_derive(), intwf_divide(), intwf_getvalue(), intwf_integrate(), intwf_multiply(), intwf_print(), intwf_resample(), intwf_reset(), intwf_scale(), intwf_setvalues(), intwf_subset(), intwf_subtract(), normalise_filter(), nr_fit(), nr_four1(), nr_gammln(), nr_gammq(), nr_gcf(), nr_gser(), nr_median(), nr_realft(), nr_seed(), nr_select(), postprocess_waveform(), print_filter(), process_caltone(), process_diode(), process_dipole(), process_monopole(), process_waveform(), realfft(), rf_addLO(), rf_amplify(), rf_amplify_complex(), rf_mixer(), rf_phase_shifter(), rf_rectify(), setup_calibration(), wfstat_print(), wfstat_reset(), and zplane_transform().
EXTERN void bpm_warning (char * msg, char * f, int l)
Prints an warning message in a standard format
Parameters:
msg the error messages, without end of line character
f the file position (__FILE__)
l the line in the file (__LINE__)
Returns:
void
Definition at line 9 of file bpm_warning.c.
References libbpm_evtnum.
Referenced by complexfft(), complexwf_add(), complexwf_delete(), complexwf_divide(), complexwf_getamp(), complexwf_getimag(), complexwf_getphase(), complexwf_getreal(), complexwf_multiply(), complexwf_setimag(), complexwf_setreal(), complexwf_subtract(), create_filter(), doublewf_add(), doublewf_basic_stats(), doublewf_delete(), doublewf_divide(), doublewf_multiply(), doublewf_subtract(), get_IQ(), get_mode_amplitude(), get_t0(), intwf_add(), intwf_delete(), intwf_divide(), intwf_multiply(), intwf_subtract(), nr_gcf(), nr_gser(), process_caltone(), process_waveform(), and realfft().